name: Build Container and deploy to AWS ECR 
run-name: Deploy by 🚀 ${{ github.actor }} 🤖
on:
  push:
    branches:
      - main

env:
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    needs: TF-Build-and-Test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v5.1.0
      - uses: unfor19/install-aws-cli-action@v1

      - run: mkdir -p ~/.aws/
      - run: echo "[techstarter]" > ~/.aws/credentials
      - run: echo "aws_access_key_id=$AWS_ACCESS_KEY" >> ~/.aws/credentials
      - run: echo "aws_secret_access_key=$AWS_SECRET_KEY" >> ~/.aws/credentials
      - run: echo "aws_session_token=$AWS_SESSION_TOKEN" >> ~/.aws/credentials
      - run: aws configure list-profiles

      - run: echo "Uploading Docker Image to ECR"
      - run: aws ecr get-login-password --region eu-central-1 --profile techstarter| docker login --username AWS --password-stdin 475032304489.dkr.ecr.eu-central-1.amazonaws.com
      - run: docker build -t pipeline .
      - run: docker tag pipeline:latest 475032304489.dkr.ecr.eu-central-1.amazonaws.com/pipeline:latest
      - run: docker push 475032304489.dkr.ecr.eu-central-1.amazonaws.com/pipeline:latest